### ISSUE TITLE
Cloud Trail logs do not log end user associated with mwaa client obtaining web login token

### ISSUE THREAD

**Issue by ajayvohra2005** [aws-samples/alb-sso-mwaa#10]
MWAA web login token is obtained by a Lambda function by assuming a role. The mwaa client in the Lambda function that obtains the web login token, currently, has no association with the email of the end user. Need to associate the MWAA client with the end user email.

**Comment by rajans163** [comment]
Hi Ajay, were you able to resolve this issue ?

**Comment by ajayvohra2005** [comment]
Yes, as noted above, this issue was resolved on Oct 11, 2023 in the hash commit 5842df10e022fc693729dc3baea8cefccc6492de.

**Comment by rajans163** [comment]
Which OIDC you are using, in my case it's azure.Also my lambda is returning multivaluequerystring as null as mentioned below.Have you done any settings for that ?

'multiValueQueryStringParameters': {}, 'multiValueHeaders': {'accept': ['text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'], 'accept-encoding': ['gzip, deflate, br, zstd'], 'accept-language': ['en-US,en;q=0.9'], 'cookie': ['session=c8cf5984-64d3-4709-bb66-d226a94aee1e.NAjiP4LOn18vEa
