### ISSUE TITLE
Issue invoking lambda with python 3.9

### ISSUE THREAD

**Issue by tomcoombs-aws** [aws-samples/alb-sso-mwaa#12]
After the Idp has issued a token and the lambda is invoked, the lambda fails with log:

“[ERROR] Runtime.ImportModuleError: Unable to import module ‘mwaa_authx’: /var/task/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory”

@tccoomb

**Comment by ramcharantej** [comment]
is this error from Lambda logs?

**Comment by tomcoombs-aws** [comment]
It is yes.
On further investigation. This error happens when the build machine is not Ubuntu as detailed in the instructions (It was Mac OS). I will close this issue
